### PR TITLE
Return error code on error

### PR DESCRIPTION
**Pull request by majchrzamemil**
Closes: [Exit with non-zero exit code on error](https://github.com/kevlarr/jrny/issues/26)
Signed-off-by: Emil Majchrzak <majchrzamemil@github.com>

### CODE REVIEW

**Comment by majchrzamemil** [comment]
Sorry for format, will revert that.

**Comment by kevlarr** [comment]
@majchrzamemil Apologies, despite being on github every day for work, I never saw a notification for this.

**Comment by majchrzamemil** [comment]
Hi, no problem ;). Finally I needed to go with other crate for managing migrations, so if you find that PR useful use it, if not feel free to close it.

**Comment by majchrzamemil** [comment]
If you'd be interested, let me know I will cleanup this and push new commit.

**Comment by kevlarr** [comment]
> Finally I needed to go with other crate for managing migrations
Smart ;) 

Even though this one has been 'complete' and 'functional' for awhile (I use it for other personal projects), it's still *really* basic.

**Comment by majchrzamemil** [comment]
> > Finally I needed to go with other crate for managing migrations
> 
> Smart ;)
> 
> Even though this one has been 'complete' and 'functional' for awhile (I use it for other personal projects), it's still _really_ basic.

I don't remember what the reason been, it is possible SSL support been missing, and it has been a blocker.

**Comment by kevlarr** [comment]
Closing this in favor of https://github.com/kevlarr/jrny/pull/32 to just use the platform-canonical code rather than 101 (which should theoretically help detect expect exit versus panic).

Thanks again @majchrzamemil, it inspired me to start back in on this after a too-long break. I'll look into SSL, too!

**Pull request closed without merging**
